### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by Pa55w0rd** [atdpa4sw0rd/Search-Tools#2]
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19042 暂缺 Build 19042
PYTHON:       3.8.0
运行闪退

**Comment by atdpa4sw0rd** [comment]
python库是否都安装了？

**Comment by Pa55w0rd** [comment]
> python库是否都安装了？

最新版仍然会报错闪退
**1.  已解决**
 Traceback (most recent call last):
  File "search_main.py", line 532, in run
    book.save('./result/'+save_xls)
  File "E:\pentest_tools\00_Information_Gathering\venv3\lib\site-packages\xlwt\Workbook.py", line 710, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "E:\pentest_tools\00_Information_Gathering\venv3\lib\site-packages\xlwt\CompoundDoc.py", line 262, in save
    f = open(file_name_or_filelike_obj, 'w+b')
FileNotFoundError: [Errno 2] No such file or directory: './result/20210407135019.xls'
在当前目录创建result目录
**2.  未解决**
Traceback (most recent call last):
  File "search_main.py", line 570, in run
    service = i.split(',')[1]
IndexError: list index out of range
**3. 未解决，使用定位功能闪退**
Traceback (most recent call last):
  File "search_main.py", line 2649, in run
    self.text_print.emit("<font color='#55ff00'>" + "[+]标签类别：" + host_classes[0]['tags'] + "<font>")
TypeError: can only concatenate str (not "list") to str

**Comment by atdpa4sw0rd** [comment]
传了新版本试试看
看样子是微步标签获取的有问题，新版本试一下哈，地图闪退，之前是需要百度的AK，最新版这个修复了
